/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void enable_processor_faults(void);
void task1_handler(void); // task 1
void task2_handler(void); // task 2
void task3_handler(void); // task 3
void task4_handler(void); // task 4


//initialize scheduler stack pointer to msp
__attribute ((naked)) void init_scheduler_task(uint32_t sched_top_of_stack);

// initialize system tick
void init_systick_timer(uint32_t ticK_hz);


void enable_processor_faults(void);

//initialize task stack
void init_tasks_stack(void);

//switch stack pointer to psp
__attribute ((naked)) void switch_sp_to_psp(void);

void idle_task(void);

void task_delay (uint32_t tick_count);

void unblock_tasks(void);

void update_global_tick_count(void);

uint32_t get_psp_value(void);

void schedule (void);

uint8_t current_task = 1;//task1 is running

uint32_t g_tick_count =0;


//Task Control Block
typedef struct
{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t  current_state;
	void (*task_handler)(void);
}TCB_t;

TCB_t user_tasks[MAX_TASKS];

int main(void)
{
	enable_processor_faults();

	init_scheduler_task(SCHED_STACK_START);

	init_tasks_stack();

	led_init_all();

	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	task1_handler();


    /* Loop forever */
	for(;;);
}



void enable_processor_faults(void)
{
	uint32_t *pSHCRS = (uint32_t *) 0xE000ED24;
	*pSHCRS |= ((1<<16)|(1<<17)|(1<<18));
}
void task1_handler(void); // task 1
void task2_handler(void); // task 2
void task3_handler(void); // task 3
void task4_handler(void); // task 4


//initialize scheduler stack pointer to msp
__attribute ((naked)) void init_scheduler_task(uint32_t sched_top_of_stack)
{
    __asm volatile("MSR MSP,%0": :  "r" (sched_top_of_stack)  :   );
    __asm volatile("BX LR");
}

// initialize system tick
void init_systick_timer(uint32_t ticK_hz)
{
	uint32_t *pSYST_CSR =(uint32_t *) 0xE000E010;
	uint32_t *pSYST_RVR =(uint32_t *) 0xE000E014;
	uint32_t *pSYST_CVR =(uint32_t *) 0xE000E018;



	uint32_t reload_value = (SYSTICK_TIM_CLK/ticK_hz) -1;
	*pSYST_RVR &= ~(0x00FFFFFF);	//clear reload value register
	*pSYST_RVR |= reload_value;	// set reload value

	*pSYST_CVR &= 0x00000000;	//clear current value register

	*pSYST_CSR |= ((1<<0)|(1<<1)|(1<<2));
	// set control and status register


}


//initialize task stack
void init_tasks_stack(void)
{
	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = idle_task;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;

	user_tasks[0].current_state = TASK_READY_STATE;
	user_tasks[1].current_state = TASK_READY_STATE;
	user_tasks[2].current_state = TASK_READY_STATE;
	user_tasks[3].current_state = TASK_READY_STATE;
	user_tasks[4].current_state = TASK_READY_STATE;



	uint32_t *pPsp ;
	for (int var = 0; var <= MAX_TASKS; var ++) {

		pPsp = (uint32_t *) user_tasks[var].psp_value;

		pPsp --;
		*pPsp = 0x01000000; //dummy xPSR : t bit =1

		pPsp --;
		*pPsp = (uint32_t )user_tasks[var].task_handler;// PC

		pPsp--;
		*pPsp = 0xFFFFFFFD; // LR

		for (int i = 0; i < 13; i++) {

			pPsp --;
			*pPsp = 0 ;// R0 - R12

		}

		user_tasks[var].psp_value = (uint32_t) pPsp;
		//psp = top of stack

	}


}

uint32_t get_psp_value(void)
{
	return user_tasks[current_task].psp_value;
}

//switch stack pointer to psp
__attribute ((naked)) void switch_sp_to_psp(void)
{
	//init value of psp
	__asm volatile("push {LR}");
	__asm volatile("BL get_psp_value");
	__asm volatile("pop {LR}");
	__asm volatile("MSR PSP, R0");


	//change spsel bit of control register
	__asm volatile("MOV R0, #2");
	__asm volatile("MSR CONTROL, R0");
	__asm volatile("BX LR");

}

void idle_task(void)
{
	while(1);
}

void task_delay (uint32_t tick_count)
{
	INTERRUPT_DISABLE();

	if(current_task)
	{
		user_tasks[current_task].block_count = g_tick_count + tick_count;
		user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
	}

	schedule ();

	INTERRUPT_ENABLE();
}


void schedule()
{
	uint32_t *pICSR =(uint32_t *) 0xE000ED04;
	*pICSR |= (1<<28);

}
void unblock_tasks(void)
{
	for (uint8_t var = 0; var < MAX_TASKS; var++)
	{
		if( (g_tick_count == user_tasks[var].block_count)
				&& (user_tasks[var].current_state != TASK_READY_STATE) )
		{
			user_tasks[var].current_state = TASK_READY_STATE;
		}
	}
}

void update_global_tick_count(void)
{
	g_tick_count++ ;
}



void task1_handler(void)
{
	while (1)
	{
		led_on(LED_BLUE);
		task_delay(DELAY_COUNT_125MS);
		led_off(LED_BLUE);
		task_delay(DELAY_COUNT_125MS);
	}

}
void task2_handler(void)
{
	while(1)
	{
		led_on(LED_GREEN);
		task_delay(DELAY_COUNT_250MS);
		led_off(LED_GREEN);
		task_delay(DELAY_COUNT_250MS);
	}

}
void task3_handler(void)
{
	while(1)
	{
		led_on(LED_ORANGE);
		task_delay(DELAY_COUNT_1000MS);
		led_off(LED_ORANGE);
		task_delay(DELAY_COUNT_1000MS);
	}

}
void task4_handler(void)
{
	while(1)
	{
		led_on(LED_RED);
		task_delay(2000);
		led_off(LED_RED);
		task_delay(2000);
	}

}

void SysTick_Handler(void)
{
	// increase global tick count
	update_global_tick_count();

	//base on tick count unblock task on time
	unblock_tasks();

	//pend the pend sv handler to switch context
	schedule();

}

__attribute__((naked)) void PendSV_Handler(void)
{
	__asm volatile(
			"MRS R0,PSP				\n"
			//mov current value of PSP to R0 ( because interrupt using msp )
			"STMDB R0!, {R4-R11}	\n"
			// xPSR / PC / LR / R12 / R3 / R2 / R1 / R0 , value of psp is addres of R0
			//Use register r0 as the reference point to store data.
			// save SF2 of current task
			"PUSH  {LR}				\n"
			// Push LR cause this is interrupt handler jump to other function loss LR
			"BL save_psp_value		\n"
			//save current value of psp back to TCB of current task
			"BL update_next_task	\n"
			// change to next task
			"BL get_psp_value		\n"
			//get psp value of next task from tcb to R0 (aapcs)
			"LDMIA R0!,{R4-R11}		\n"
			//retrieve SF2 of current task
			"MSR PSP,R0				\n"
			//take psp value in R0 to real PSP
			"POP  {LR}				\n"
			//pop back LR
			"BX LR				\n"
			//jump to LR
	);

}

void save_psp_value(uint32_t psp_value)
{
	user_tasks[current_task].psp_value = psp_value;
}

void update_next_task(void)
{
	int state=0;

	for (uint8_t var = 0;  var < MAX_TASKS;  var++) {

		current_task++;
		current_task %= MAX_TASKS;
		state = user_tasks[current_task].current_state;

		if( (state ==TASK_READY_STATE) && (current_task !=0))
		{
			break;
		}
	}

	if(state != TASK_READY_STATE)
	{
		current_task = 0;
	}

}









