/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include<stdio.h>
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void genarate_interrupt()
{
	uint32_t *pSTIR=(uint32_t *)0XE000EF00;
	uint32_t *pISER0=(uint32_t *)0XE000E100;

	// enable IRQ3 interrupt
	*pISER0|=(1<<3);
	// enable IRQ3 interrupt
	*pSTIR=(3&0x1FF);

}



int main(void)
{
	printf("in thread mode: before interrupt\n");

	genarate_interrupt ();

	printf("in thread mode: after interrupt\n");
    /* Loop forever */
	for(;;);
}

void RTC_WKUP_IRQHandler(void)
{

	printf("in handler mode: ISR\n");
	while(1);
}

